---
title: TK Design Robotics
date: 2019-01-20
---

author: Rowguard
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Learning how to design robots for human use; prothesis and human-exoskeletons. A desire to create the future only dreamed of in science fiction.
The ultimate goal is one day make humanoid robots.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
